Refactor
surfstudio/flutter-bottom-sheet pull request #1
Opened 2021-07-27 11:43 UTC by VVPAK

- Исправлены замечание анализатора.

2021-07-27 14:24 UTC, MbIXjkee requested changes
WIP
Нужно будет еще обсудить, пока попробуй исправить текущие замечания

2021-07-27 14:24 UTC, MbIXjkee commented on lib/src/core/interactive_sheet.dart
> +class InteractiveSheet extends StatefulWidget {
Ниже тоже есть примеры, давай пока оставим нейминг в покое и откатим на тот который был, по неймингу если есть вопросы - сделаем отдельную итерацию

2021-07-27 18:02 UTC, VVPAK commented on example/ios/Runner.xcodeproj/project.pbxproj
> +						DevelopmentTeam = 7MU7K6222M;
Тестил на телефоне. т.к не открывалась клавиатура на эмуляторе

2021-07-27 18:02 UTC, VVPAK commented on example/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.example.asdqwe;
Аналогично подписи, не example.example недоступен

2021-07-27 18:04 UTC, VVPAK commented on lib/src/core/interactive_sheet.dart
> +class InteractiveSheet extends StatefulWidget {
По этому поводу пока под вопросом, этот пункт больше касается рефактора в целом. Название нормальное пока не придумал, еще в процессе. Редактор еще не закончил. По неймингу название слишком длинное и думаю непонятное.

2021-07-27 18:06 UTC, VVPAK commented on lib/src/core/interactive_sheet.dart
> +class InteractiveSheetState extends State<InteractiveSheet> {
Стейт используется в документации interactive_sheet_extent

2021-07-27 18:07 UTC, VVPAK commented on example/ios/Flutter/AppFrameworkInfo.plist
> -  <string>8.0</string>
При запуске на телефоне версия скорее всего поднялась

2021-07-28 08:04 UTC, VVPAK commented on lib/src/core/core.dart
> +export 'inherited_reset_notifier.dart';
Чтобы не импортировать много разных файлов

2021-07-29 08:28 UTC, MbIXjkee commented on lib/src/core/core.dart
> +export 'inherited_reset_notifier.dart';
Не стоит - смотри, если ты импортируешь все эти файлы отдельно, и из них по факту будет использоваться 1, будет ли ругаться анализатор на остальные импорты и с чем это связано? Тут ты реализуешь ровно такую ситуацию. Реэкспорты нужно использовать очень продумано и они уместны сосем не везде

2021-07-29 08:28 UTC, MbIXjkee commented on lib/src/core/inherited_reset_notifier.dart
> +class InheritedResetNotifier extends InheritedNotifier<ResetNotifier> {
Перенос документации конструктора это не совсем то что требовалось. Надо описать назначение этого файла, для этого конечно нужно предварительно точно разобраться с тем зачем эта сущность вообще введена

2021-09-14 12:47 UTC, closed without merging