feat!: replacing part of the functionality with DraggableScrollableSheet
surfstudio/flutter-bottom-sheet pull request #33
Opened 2022-02-15 14:22 UTC by UnusovOleg

Replacing part of the functionality with DraggableScrollableSheet

BREAKING CHANGE: replace FlexibleScrollNotifier

2022-02-17 10:12 UTC, MbIXjkee requested changes

2022-02-17 10:12 UTC, MbIXjkee commented on lib/src/flexible_bottom_sheet.dart
> +              // checking the case when the keyboard is open
тут комент водит в заблуждение вроде, это же для ситуации когда клавиатура уже открыта

2022-02-18 08:23 UTC, UnusovOleg commented on lib/src/widgets/change_insets_detector.dart
> +    super.didChangeDependencies();
+

2022-02-18 08:23 UTC, UnusovOleg commented on lib/src/widgets/change_insets_detector.dart
> +    if (MediaQuery.of(context).viewInsets.bottom != lastInsets) {
+

2022-02-18 08:23 UTC, UnusovOleg commented on lib/src/flexible_bottom_sheet.dart
> +  /// scroll callback
+

2022-02-18 08:24 UTC, UnusovOleg commented on lib/src/flexible_bottom_sheet.dart
> +              child: _Content(
+

2022-02-20 13:07 UTC, MbIXjkee approved these changes
LGTM

2022-02-20 13:27 UTC, merged