fix(): snackbar issue fix
surfstudio/flutter-bottom-sheet pull request #76
Opened 2023-02-02 10:41 UTC by GalimzyanovDanil

## Checklist

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Is there an existing issue for this PR?
https://github.com/surfstudio/flutter-bottom-sheet/issues/69
- [ ] Have the files been linted and formatted?
- [ ] Have the docs been updated to match the changes in the PR?
- [ ] Have the tests been updated to match the changes in the PR?
- [ ] Have you run the tests locally to confirm they pass?

## Changes

### How does this PR fix the problem?
Since the snackbar is shown relative to the current active scaffold, it was necessary to remove the scaffold from the widget tree, leaving the possibility of displaying the snackbar on top of the bottom sheet.
A new parameter was added that allows you to remove the scaffold from the bootom sheet widget tree.

With Scaffold in widget tree.

https://user-images.githubusercontent.com/86564275/216302668-8ac7c46a-517c-498d-ae1a-8a7c1d101e88.mov

Without Scaffold in widget tree.

https://user-images.githubusercontent.com/86564275/216302705-5adec5d6-eefe-4733-9b32-22a140ecb8b5.mov

2023-02-14 06:13 UTC, dshevchenkoo commented
@GalimzyanovDanil exception on analysis
check flutter version for package, maybe need to update?

2023-02-14 06:37 UTC, GalimzyanovDanil commented
> @GalimzyanovDanil exception on analysis check flutter version for package, maybe need to update?

I can fix depracted fields, but this dont resolve all problems. Also needed upgrade surf_lint_rules package.

2023-07-31 14:56 UTC, internetova commented
![2023-07-31 17 51 22](https://github.com/surfstudio/flutter-bottom-sheet/assets/39735343/089b0e7a-a7eb-4901-b82d-99163713f199)

2023-08-01 06:46 UTC, mpkander commented
@internetova Please, change target to dev

2023-08-01 06:46 UTC, mpkander requested changes
@internetova Please, change target to dev

2023-08-01 07:48 UTC, mpkander requested changes
Looks like not breaking. Add CHANGELOG info for future version

2023-08-02 07:43 UTC, mpkander commented on example/lib/standard_bottom_sheet_example.dart
> +      isRegisterScaffold: false,
Can we change name to be more clear? 

For example, `useRootScaffold`

2023-08-02 13:40 UTC, mpkander approved these changes

2023-08-02 14:29 UTC, merged