SNP-707: update flutter version
surfstudio/flutter-bottom-sheet pull request #90
Opened 2023-08-04 15:37 UTC by internetova

## Changes
* Updates minimum Flutter version to 3.0.0
* Updates minimum surf_lint_rules version to 3.0.0
*  Fixed dart analysis

## Checklist for self-check
- [ ] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [ ] The author is marked as an assigne and assigned mandatory reviewers.
- [ ] Required labels marked
- [ ] Specified related tasks and/or related PRs.
- [ ] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [ ] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2023-08-07 08:29 UTC, ViktorJasch approved these changes

2023-08-07 08:29 UTC, ViktorJasch commented on example/lib/bottom_sheet_based_on_content_height.dart
>    Widget build(BuildContext context) {
К проекту подключен member-ordering линтер, который ругается на этот метод. Вижу что изменения были сделаны не в рамках этой задачи, но возможно, пока изменений немного, стоит пофиксить в этом месте замечания линтера

2023-08-14 16:03 UTC, alexey-fetisov commented on test/sticky_bottom_sheet_test.dart
> -//     http://www.apache.org/licenses/LICENSE-2.0
В лицензии апача в оригинале  2.0, а не 2. И в ссылках и остальных местах, где прописана версия.

2023-08-14 16:04 UTC, alexey-fetisov commented on test/bottom_sheet_test.dart
> +//     http://www.apache.org/licenses/LICENSE-2
В лицензии апача в оригинале 2.0, а не 2. И в ссылках и остальных местах, где прописана версия.

2023-08-15 06:26 UTC, mpkander approved these changes

2023-08-15 06:27 UTC, mpkander commented on test/bottom_sheet_test.dart
> +//     http://www.apache.org/licenses/LICENSE-2
@internetova Need to fix

2023-08-15 08:34 UTC, mpkander requested changes
Fix the license issue

2023-08-15 13:42 UTC, merged